apiVersion: v1
kind: Pod
metadata:
  name: consumer
  labels:
    name: consumer
spec:
  containers:
  - name: consumer
    image: nginx
    volumeMounts:
      - mountPath: /var/app
        name: ext-service-secret  
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
   - name: ext-service-secret
     secret:
      secretName: ext-service-secret  