apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  labels:
    name: security-context-demo
spec:
  serviceAccountName: "monitoring"
  containers:
  - name: security-context-demo
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    securityContext:
      capabilities:
        add:
          - SYS_TIME
 