apiVersion: v1
kind: Pod
metadata:
  name: loop
  labels:
    name: loop
spec:
  containers:
  - name: loop
    image: busybox
    args:
      - /bin/sh
      - -c
      - for i in {1..10}; do echo 'Welcome $i times'; done
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    restartPolicy: Never
