apiVersion: v1
kind: Pod
metadata:
  name: data-exchange
spec:
  containers:
  - name: main-app
    image: busybox
    command: ["sh","counter=1; while true; do touch '/var/app/data/$counter-data.txt'; counter=$((counter+1)); sleep 30; done" ]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
