apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    team: artemidis
    tier: backend
  annotations:
    deployer: makkasbed
  name: pod-3
spec:
  containers:
  - image: nginx
    name: pod-3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
