apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web-server
  name: web-server
spec:
  containers:
  - image: nginx
    name: web-server
    startupProbe:
      httpGet:
        port: 80
        path: /
    readinessProbe:
      httpGet:
        port: 80
        path: /
      initialDelaySeconds: 5
    livenessProbe:
      httpGet:
        port: 80
        path: /
      initialDelaySeconds: 10
      periodSeconds: 30      
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
