apiVersion: v1
kind: Pod
metadata:
  name: in-loop
  labels:
    name: in-loop
spec:
  containers:
  - name: in-loop
    image: busybox
    args:
      - /bin/sh
      - -c
      - while true; do echo date; done
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      
